name: MATH3094
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.11.0
  - aiohttp=3.6.3
  - argon2-cffi=20.1.0
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - bokeh=2.2.3
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - cachetools=4.2.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.4
  - colorcet=2.0.5
  - cryptography=3.3.1
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.4
  - gast=0.4.0
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.2
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - holoviews=1.14.0
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - keras=2.4.3
  - keras-applications=1.0.8
  - keras-base=2.4.3
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.3
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - multidict=4.7.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - notebook=6.1.6
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - packaging=20.8
  - pandas=1.2.0
  - pandoc=2.11
  - pandocfilters=1.4.3
  - panel=0.10.3
  - param=1.10.1
  - parso=0.7.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - protobuf=3.13.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyct=0.4.8
  - pygments=2.7.4
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.5
  - pyviz_comms=2.0.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7
  - scipy=1.5.2
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=51.1.2
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.3.0
  - termcolor=1.1.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.55.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
